services:
  api:
    image: ghcr.io/upsc-plantgenie/plantgenie-api/fastapi-backend:v0.4.0
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - "fastapi"
      - "dev"
      - "/app/src/plantgenie_api/main.py"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reload"
    env_file:
      - .env.shared
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NEO4J_URI=bolt://neo4j:7687
    volumes:
      - "${HOST_DATA_DIR}:/opt/pg-application-data:rw"
      - ".env.shared:/app/.env.shared:ro"
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      neo4j:
        condition: service_healthy
    networks:
      - plantgenie_network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./pyproject.toml

  celery_worker:
    build:
      context: .
      dockerfile: packages/task-queue/Dockerfile
    image: ghcr.io/upsc-plantgenie/plantgenie-api/celery-worker:v0.4.0
    entrypoint:
      - "celery"
      - "-A"
      - "task_queue.celery.app"
      - "worker"
      - "--loglevel"
      - "debug"
    env_file:
      - .env.shared
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - "${HOST_DATA_DIR}:/opt/pg-application-data:rw"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - plantgenie_network
    develop:
      watch:
        - action: sync+restart
          path: ./packages/task-queue/src
          target: /app/src
        - action: rebuild
          path: ./packages/task-queue/pyproject.toml

  rabbitmq:
    image: rabbitmq:4.2-management # an ubuntu image base
    ports:
      - "5672:5672"
      - "15672:15672"  # rabbitmq management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - plantgenie_network

  redis:
    image: redis:8.4-bookworm
    ports:
      - "6379:6379"
    networks:
      - plantgenie_network

  neo4j:
    image: neo4j:2026.01.4-community-trixie
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/guest123
      NEO4J_PLUGINS: '["graph-data-science"]'
    volumes:
      - /opt/neo4j/logs:/logs
      - /opt/neo4j/data:/data
      - /opt/neo4j/import:/import
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p guest123 'RETURN 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      - plantgenie_network

networks:
  plantgenie_network:
    driver: bridge
