// BlastDatabase nodes from database-imports/blast-databases.csv, linked to the
// Assembly (genome) or Annotation (cds, transcripts, proteins) they belong to.
//
// Requires assembly-load.cypher and annotation-load.cypher to have run first.
// The CSV is generated by scripts/neo4j/generate-blast-databases-csv.py.
//
// path is the database basename relative to the knowledge root, not a file
// that exists: BLAST wants 'picab/v2/blast/nucl/genome.fa' while only
// genome.fa.nsq and friends are on disk. The program is not stored because it
// follows from moleculeType - nucl serves blastn, tblastn and tblastx, prot
// serves blastp and blastx.

CREATE CONSTRAINT blast_database_id IF NOT EXISTS FOR (b:BlastDatabase) REQUIRE b.id IS UNIQUE;

// Clear existing blast databases (safe to re-run)
MATCH (b:BlastDatabase)
CALL (b) { DETACH DELETE b } IN TRANSACTIONS OF 1000 ROWS;

LOAD CSV WITH HEADERS FROM 'file:///blast-databases.csv' AS row
OPTIONAL MATCH (a:Assembly {id: row.owner})
OPTIONAL MATCH (n:Annotation {id: row.owner})
WITH row, coalesce(a, n) AS owner
CREATE (owner)-[:HAS_BLAST_DB]->(:BlastDatabase {
  id:           row.id,
  sequenceType: row.sequenceType,
  moleculeType: row.moleculeType,
  name:         row.name,
  path:         row.path
});

// Verification - expect 20 databases, 5 on assemblies and 15 on annotations
MATCH (owner)-[:HAS_BLAST_DB]->(b:BlastDatabase)
RETURN labels(owner)[0] AS ownerType, count(b) AS databaseCount
ORDER BY ownerType;
